services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: digital-twin-backend
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-fsS', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
